import assert from "node:assert/strict";
import { renderMarketingText, wrapMarketingEmail } from "@workspace/api-zod";
const render = (text: string, name?: string) => renderMarketingText(text, "https://portal.example", name);
const image = render("![Imagem](/api/uploads/emails/Arcos Laranja e Cinza.jpg)");
assert.match(image, /<img src="https:\/\/portal.example\/api\/uploads\/emails\/Arcos%20Laranja%20e%20Cinza.jpg"/);
assert.doesNotMatch(image, /<a /);
assert.equal((render("![A](/a.jpg)\n\n![B](https://cdn.example/b.jpg)").match(/<img /g) || []).length, 2);
assert.match(render("[Painel](/artista/login)"), /<a href="https:\/\/portal.example\/artista\/login"/);
assert.match(render("# Olá, {{nome}}!\n\n**Novidades** e *música*", "Ana & Bia <3"), /Ana &amp; Bia &lt;3/);
assert.match(render("{{nome}} {{name}}"), /\{\{nome\}\} \{\{nome\}\}/);
assert.match(render("{{nome}}", "$&"), /\$&amp;/);
assert.match(render('<script>alert("x")</script>'), /&lt;script&gt;/);
assert.doesNotMatch(render('[Clique](javascript:alert) ![X](data:text/html,bad)'), /href=|src=/);
assert.match(render('![" onerror="alert](/image.jpg)'), /alt="&quot; onerror=&quot;alert"/);
assert.match(render("## Título\n\nLinha 1\nLinha 2"), /<h2 .*Título<\/h2>.*Linha 1<br \/>Linha 2/);
const mail = wrapMarketingEmail(image);
assert.match(mail, /#f5c518/);
assert.match(mail, /role="presentation"/);
assert.ok(mail.includes(image));
console.log("PASS: images, absolute and encoded URLs, links, formatting, safe personalization and shared template");
