import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import songsRouter from "./songs";
import settingsRouter from "./settings";
import artistsRouter from "./artists";
import plansRouter from "./plans";
import interestsRouter from "./interests";
import profileRouter from "./profile";
import artistSongsRouter from "./artist-songs";
import adminRouter from "./admin";
import paymentsRouter from "./payments";
import genresRouter from "./genres";
import authPasswordRouter from "./auth-password";
import bannersRouter from "./banners";
import citiesRouter from "./cities";
import playlistsRouter from "./playlists";
import galleriesRouter from "./galleries";
import sitemapRouter from "./sitemap";
import couponsRouter from "./coupons";
import contatosRouter from "./contatos";
import custosRouter from "./custos";
import receitasRouter from "./receitas";
import eventosRouter from "./eventos";
import ajudaRouter from "./ajuda";
import audicoesRouter from "./audicoes";
import liberacoesRouter from "./liberacoes";
import financeiroRouter from "./financeiro";
import songComposersRouter from "./song-composers";

import exitFeedbackRouter from "./exit-feedback";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(songsRouter);
router.use(settingsRouter);
router.use(artistsRouter);
router.use(plansRouter);
router.use(interestsRouter);
router.use(profileRouter);
router.use(artistSongsRouter);
router.use(adminRouter);
router.use(paymentsRouter);
router.use(genresRouter);
router.use(authPasswordRouter);
router.use(bannersRouter);
router.use(citiesRouter);
router.use(playlistsRouter);
router.use(galleriesRouter);
router.use(sitemapRouter);
router.use(couponsRouter);
router.use(contatosRouter);
router.use(custosRouter);
router.use(receitasRouter);
router.use(eventosRouter);
router.use(ajudaRouter);
router.use(audicoesRouter);
router.use(liberacoesRouter);
router.use(financeiroRouter);
router.use(songComposersRouter);
router.use(exitFeedbackRouter);

export default router;
